### ISSUE TITLE
Crash after update to .Net9

### ISSUE THREAD

**Issue by Grzesik** [afriscic/BarcodeScanning.Native.Maui#112]
When I start the BarcodeScanning.Native.Maui Version=2.0.0 for .Net Maui Version 9, the app crashes, when I close the preview window:

System.NotSupportedException: 'Unable to activate instance of type BarcodeScanning.BarcodeAnalyzer from native handle 0x7ff7cfc138 (key_handle 0x5ec2f95).'

I tested it on Android 13, Pixel 4a

It worked fine in the older Version 1.6.0 in .Net Maui 8. The only problem was, when I started the preview for the first time it freeses. It happend only seldom and always for the first time after some longer perion of time (like next day).

**Comment by afriscic** [comment]
Try to set `CameraEnabled` to `false` and the wait a little bit using `await Task.Delay(100)` before navigating away.

As for the freeze, in my experience, it only happens when the Debugger is attached.

**Comment by Grzesik** [comment]
I added the delay, unfortunatelly I have still the same problem on Android:
System.NotSupportedException: 'Unable to activate instance of type BarcodeScanning.BarcodeAnalyzer from native handle 0x7ff7cfc138 (key_handle 0x5dfe99a).' 
The freeze of the View happens in a store app unfortunatelly, but I don't have there the delay befor navigating back.

**Comment by afriscic** [comment]
I tested this on Barcodescanning.Test project and only time i get the exception is if `CameraEnabled` isn't set to `false` before navigating back. Please share some of your code if it differs from the code below.

Working code (for me):
```
private async void CameraView_OnDetectionFinished(object sender, OnDetectionFinishedEventArg e)
{
      if (e.BarcodeResults.Count > 0)
      {
          Barcode.CameraEnabled = false;
          await Shell.Current.GoToAsync("..");
      }
}
```

And also working:
```
protected override void OnDisappearing()
{
      base.OnDisappearing();
      Barcode.CameraEnabled = false;
}
private async void CameraView_OnDetectionFinished(object sender, OnDetectionFinishedEventArg e)
{
      if (e.BarcodeResults.Count > 0)
          await Shell.Current.GoToAsync("..");
}
```

**Comment by Grzesik** [comment]
[ScannerMauiApp2.zip](https://github.com/user-attachments/files/17873351/ScannerMauiApp2.zip)

Hi,
thank you for your quick answer. I added an sample app, which also crash, when I close the ScannerPage with the "X" on the top left page side.

**Comment by afriscic** [comment]
I took a quick look at your code and the diagnosis is the same... it looks like the Handler gets disconnected and everything disposed before the camera stops.
Unfortunately i don7t have time to do the whole debugging, especially as I don't have any experience with the packages that you are using for MVVM model.
Overriding `OnDisappearing()` and setting `CameraEnabled = false;` in the code behind of the page should fix this issue.

**Comment by Grzesik** [comment]
[ScannerMauiApp2.zip](https://github.com/user-attachments/files/17903857/ScannerMauiApp2.zip)

Hi, I updated the project to the latest Nuget Package & changed the binding to the CameraEnabled  (deleted the Mode property) and the QR Code Scanner works now very well!
Thank you for your help!

**Comment by Grzesik** [comment]
See last comment

**Comment by Ghostbird** [comment]
Hmm... I'm still having this problem in the .NET 9 / 2.1.1 variant. We were using 1.4.0 in .NET 8 and that worked just fine. Now it always crashes when we navigate away. `CameraEnabled` was always already set to false before we do that, otherwise it wouldn't work in .NET 8 / 1.4.0 either.

**Comment by Grzesik** [comment]
I tested it onl ywith Android 13 / Pixel 4a. You can also enable/disable the camera, when the page receives OnAppearing / OnDisappearing in code behind.

**Comment by Ghostbird** [comment]
I found a workaround:

This used to be the correct way to do it in the 1.4.0 / .NET 8 variant, but no longer works now:

```csharp
// Clean up barcode scanner page before we navigate away.
scanView.TapToFocusEnabled = false;
scanView.TorchOn = false;
scanView.OnDetectionFinished -= OnScan;
scanView.CameraEnabled = false;
// Disconnect handler as documented to prevent memory leaks
scanView.Handler?.DisconnectHandler();
scanView = null;
```

To get it to work again, I must now add this ugly hack:


```csharp
// Clean up barcode scanner page before we navigate away.
scanView.TapToFocusEnabled = false;
scanView.TorchOn = false;
scanView.OnDetectionFinished -= OnScan;
scanView.CameraEnabled = false;
// Workaround for BarcodeScanning.Native.Maui #112
await Task.Delay(100);
// Disconnect handler as documented to prevent memory leaks
scanView.Handler?.DisconnectHandler();
scanView = null;
```

So it turns out, it doesn't have anything to do with the navigation. I must now wait before disconnecting the handler. Whereas previously, I had to disconnect it first.

**Comment by afriscic** [comment]
As there were basically three different threads that were involved in barcode detection on Android it looks like there is some race condition where `BarcodeAnalyzer` gets disposed but `_barcodeScanner.Process` is still running in the background and then trying to access the disposed instance of `BarcodeAnalyzer` as it is registered as `OnSuccessListener` and `OnCompleteListener`.

I guess this happens on 9.0 more often as `DisconnectHandler()` is called automatically ([link](https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#handler-disconnection)).

I am planning to do a rework of the `BarcodeAnalyzer` (again...) on Android to use `TasksClass.Await(task)` to make everything run synchronously on the same background thread. This should prevent at least some of the crashes.
